name = "PDE"
version = "0.1.0"
license = "license"
author = "Elliot Jmaes"
maintainer = "ejb321@ic.ac.uk"
copyright = "Copyright 2024, Elliot Jmaes"


[build]
auto-executables = true
auto-tests = true
auto-examples = true
module-naming = false

# adds lapack and blas packages
link = ["blas", "lapack"]



[install]
library = false

[fortran]
implicit-typing = false
implicit-external = true
source-form = "free"

[dependencies]

[dev-dependencies]
test-drive.git = "https://github.com/fortran-lang/test-drive"
test-drive.tag = "v0.4.0"


[library]
source-dir="src"
build-script="my_build_script"